### ISSUE TITLE
Allow to specify name and schema for the migrations table

### ISSUE THREAD

**Issue by danielbuechele** [ruffythepirate/sql-apply#1]
Currently it is assumed the `migrations` table is always called like this and it's in the `public` schema of the database. Maybe we can provide a way to make this configurable. For my use-case the migrations table can't be in the `public` schema.

PS: Part of the reason I open this issue is to say hi 👋. I just stumbled upon this project and it looks quite useful to me. Great work! I might be able to contribute a little in the future as well. I have a few ideas and questions, should I create issue for them, even if they are technically not an issue but a question, or should I use a different channel?

**Comment by ruffythepirate** [comment]
Hey Daniel, nice to hear from you, hi :). It's perfect you write here with your advice as well, I'd know no better place to track the dialogue and ideas.

I'm a bit crammed at the moment but I'll likely take a closer look this weekend. Spontaneously I would expect the migration table to land in the default schema of the client that is sent to the runMigrations function. If you'd need that the migration table lands in a different schema than the one that the migrations are applied though we'd need to look a bit closer to find a solution though.

**Comment by ruffythepirate** [comment]
Fixed in 2.1.1. There seems to be an issue if you want the migations table to be in a different schema from what you are creating with your migration scripts, but now at least it's possible to specify which schema to use.
