### ISSUE TITLE
Using common Postgres env vars

### ISSUE THREAD

**Issue by danielbuechele** [ruffythepirate/sql-apply#3]
Postgres has a set of environment variables defined for connection: https://www.postgresql.org/docs/9.1/libpq-envars.html
Maybe we could make use of them as default values, when no other values are set.

The `pg` modules is actually already supporting them: https://node-postgres.com/features/connecting

**Comment by ruffythepirate** [comment]
When it comes to the internals of the project I want it to be "stupid" regarding what client it receives (I know at the moment it's tied to postgres syntax, but at some point I'd probably look at making it more agnostic to what's on the outside. That being said, if a wrapper is added for the cli, then this wrapper would use the environment variables

**Comment by ruffythepirate** [comment]
This works now when using it from CLI, but you can't run it using npx, because npx doesn't transfer the environment. instead you have to run npm i -g sql-apply and then run `sql-apply migrate -m <dir>`
